INSERT INTO make (name)
VALUES
    ('Abarth'),
    ('Alfa Romeo'),
    ('Audi'),
    ('Bentley'),
    ('BMW'),
    ('BYD'),
    ('Citroen'),
    ('Cupra'),
    ('Dacia'),
    ('DS Automobiles'),
    ('Ferrari'),
    ('Fiat'),
    ('Ford'),
    ('Genesis'),
    ('Honda'),
    ('Hyundai'),
    ('Infiniti'),
    ('Isuzu'),
    ('Jaguar'),
    ('Jeep'),
    ('Kia'),
    ('Lamborghini'),
    ('Land Rover'),
    ('Lexus'),
    ('Lotus'),
    ('Maserati'),
    ('Mazda'),
    ('McLaren'),
    ('Mercedes-Benz'),
    ('MG'),
    ('Mini'),
    ('Mitsubishi'),
    ('Nissan'),
    ('Peugeot'),
    ('Polestar'),
    ('Porsche'),
    ('Renault'),
    ('Rolls-Royce'),
    ('SEAT'),
    ('Skoda'),
    ('Smart'),
    ('SsangYong'),
    ('Subaru'),
    ('Suzuki'),
    ('Tesla'),
    ('Toyota'),
    ('Vauxhall'),
    ('Volkswagen'),
    ('Volvo')
ON CONFLICT (name) DO NOTHING;
