CREATE TABLE vehicle_images (
    Id SMALLINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	ImagePath NVARCHAR(255) NOT NULL,
	IsMainImage BOOLEAN DEFAULT FALSE,
	CONSTRAINT FK_VehicleImages_Vehicle FOREIGN KEY (VehicleId) REFERENCES Vehicle(Id)
);
